name: ServiceNow Case Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  SERVICENOW_INSTANCE: ${{ secrets.SERVICENOW_INSTANCE }}
  SERVICENOW_USERNAME: ${{ secrets.SERVICENOW_USERNAME }}
  SERVICENOW_PASSWORD: ${{ secrets.SERVICENOW_PASSWORD }}

jobs:
  create-and-monitor-case:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Run your application/tests
      run: |
        # Replace this with your actual code execution
        echo "Running application code..."
        npm install  # or your build/test commands
        npm test
        
    - name: Create ServiceNow Case
      id: create_case
      run: |
        # Create case in ServiceNow
        RESPONSE=$(curl -s -X POST \
          "https://${SERVICENOW_INSTANCE}/api/now/table/sc_request" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "Authorization: Basic $(echo -n ${SERVICENOW_USERNAME}:${SERVICENOW_PASSWORD} | base64)" \
          -d '{
            "short_description": "GitHub Action Deployment Request - '"${{ github.repository }}"'",
            "description": "Automated deployment request from GitHub Action\nRepository: '"${{ github.repository }}"'\nCommit: '"${{ github.sha }}"'\nBranch: '"${{ github.ref_name }}"'\nWorkflow: '"${{ github.workflow }}"'",
            "priority": "3",
            "state": "-5",
            "requested_for": "'"${SERVICENOW_USERNAME}"'",
            "request_state": "submitted_for_approval"
          }')
        
        # Extract request number and sys_id
        REQUEST_NUMBER=$(echo $RESPONSE | jq -r '.result.number')
        REQUEST_SYS_ID=$(echo $RESPONSE | jq -r '.result.sys_id')
        
        echo "request_number=$REQUEST_NUMBER" >> $GITHUB_OUTPUT
        echo "request_sys_id=$REQUEST_SYS_ID" >> $GITHUB_OUTPUT
        echo "Created ServiceNow Request: $REQUEST_NUMBER"
        
    - name: Monitor Request Status
      id: monitor_request
      run: |
        REQUEST_SYS_ID="${{ steps.create_case.outputs.request_sys_id }}"
        REQUEST_NUMBER="${{ steps.create_case.outputs.request_number }}"
        MAX_ATTEMPTS=30
        SLEEP_INTERVAL=60
        
        echo "Monitoring request $REQUEST_NUMBER for approval..."
        
        for i in $(seq 1 $MAX_ATTEMPTS); do
          echo "Check #$i - Polling request status..."
          
          RESPONSE=$(curl -s -X GET \
            "https://${SERVICENOW_INSTANCE}/api/now/table/sc_request/${REQUEST_SYS_ID}" \
            -H "Accept: application/json" \
            -H "Authorization: Basic $(echo -n ${SERVICENOW_USERNAME}:${SERVICENOW_PASSWORD} | base64)")
          
          REQUEST_STATE=$(echo $RESPONSE | jq -r '.result.request_state')
          APPROVAL=$(echo $RESPONSE | jq -r '.result.approval // "not_requested"')
          
          echo "Request $REQUEST_NUMBER - State: $REQUEST_STATE, Approval: $APPROVAL"
          
          # Check request states for sc_request
          case $REQUEST_STATE in
            "closed_complete")
              if [ "$APPROVAL" = "approved" ]; then
                echo "✅ Request $REQUEST_NUMBER has been APPROVED and COMPLETED!"
                echo "status=approved" >> $GITHUB_OUTPUT
                exit 0
              else
                echo "❌ Request $REQUEST_NUMBER completed but not approved!"
                echo "status=completed_not_approved" >> $GITHUB_OUTPUT
                exit 1
              fi
              ;;
            "closed_rejected"|"closed_cancelled")
              echo "❌ Request $REQUEST_NUMBER has been REJECTED/CANCELLED!"
              echo "status=rejected" >> $GITHUB_OUTPUT
              exit 1
              ;;
            "closed_incomplete")
              echo "⚠️ Request $REQUEST_NUMBER closed as incomplete!"
              echo "status=incomplete" >> $GITHUB_OUTPUT
              exit 1
              ;;
          esac
          
          # Also check pure approval status
          if [ "$APPROVAL" = "approved" ]; then
            echo "✅ Request $REQUEST_NUMBER has been APPROVED!"
            echo "status=approved" >> $GITHUB_OUTPUT
            exit 0
          elif [ "$APPROVAL" = "rejected" ]; then
            echo "❌ Request $REQUEST_NUMBER has been REJECTED!"
            echo "status=rejected" >> $GITHUB_OUTPUT
            exit 1
          fi
          
          if [ $i -eq $MAX_ATTEMPTS ]; then
            echo "⏰ Timeout: Request $REQUEST_NUMBER still pending after maximum attempts"
            echo "status=timeout" >> $GITHUB_OUTPUT
            exit 1
          fi
          
          echo "Waiting ${SLEEP_INTERVAL} seconds before next check..."
          sleep $SLEEP_INTERVAL
        done
        
    - name: Print Final Results
      if: always()
      run: |
        echo "=================== SERVICENOW INTEGRATION RESULTS ==================="
        echo "Request Number: ${{ steps.create_case.outputs.request_number }}"
        echo "Request Status: ${{ steps.monitor_request.outputs.status }}"
        echo "Repository: ${{ github.repository }}"
        echo "Commit SHA: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "===================================================================="
        
    - name: Update Request with Results
      if: always()
      run: |
        STATUS="${{ steps.monitor_request.outputs.status }}"
        REQUEST_SYS_ID="${{ steps.create_case.outputs.request_sys_id }}"
        
        WORK_NOTES="GitHub Action completed with status: $STATUS\nWorkflow URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        
        curl -s -X PUT \
          "https://${SERVICENOW_INSTANCE}/api/now/table/sc_request/${REQUEST_SYS_ID}" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "Authorization: Basic $(echo -n ${SERVICENOW_USERNAME}:${SERVICENOW_PASSWORD} | base64)" \
          -d '{
            "work_notes": "'"$WORK_NOTES"'"
          }'