name: ServiceNow sc_request Test

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  SERVICENOW_INSTANCE: ${{ secrets.SERVICENOW_INSTANCE }}
  SERVICENOW_USERNAME: ${{ secrets.SERVICENOW_USERNAME }}
  SERVICENOW_PASSWORD: ${{ secrets.SERVICENOW_PASSWORD }}

jobs:
  test-servicenow:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Test ServiceNow Connection
      run: |
        echo "Testing ServiceNow connection..."
        echo "https://${SERVICENOW_INSTANCE}/api/now/table/sys_user?sysparm_limit=1"
        echo "${SERVICENOW_USERNAME}:${SERVICENOW_PASSWORD}"
        HTTP_CODE=$(curl -s -w "%{http_code}" -o /dev/null \
          "https://${SERVICENOW_INSTANCE}/api/now/table/sys_user?sysparm_limit=1" \
          -H "Authorization: Basic $(echo -n ${SERVICENOW_USERNAME}:${SERVICENOW_PASSWORD} | base64)")
        
        if [ "$HTTP_CODE" = "200" ]; then
          echo "✅ ServiceNow connection successful"
        else
          echo "❌ ServiceNow connection failed (HTTP $HTTP_CODE)"
          exit 1
        fi
        
    - name: Create Test Request
      id: create_request
      run: |
        echo "Creating test request..."
        RESPONSE=$(curl -s -X POST \
          "https://${SERVICENOW_INSTANCE}/api/now/table/sc_request" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "Authorization: Basic $(echo -n ${SERVICENOW_USERNAME}:${SERVICENOW_PASSWORD} | base64)" \
          -d '{
            "short_description": "GitHub Test Request - '"${{ github.repository }}"'",
            "description": "Test request from GitHub Actions\nRepository: '"${{ github.repository }}"'\nCommit: '"${{ github.sha }}"'\nBranch: '"${{ github.ref_name }}"'",
            "priority": "4",
            "state": "-5",
            "requested_for": "'"${SERVICENOW_USERNAME}"'",
            "request_state": "submitted_for_approval"
          }')
        
        REQUEST_NUMBER=$(echo $RESPONSE | jq -r '.result.number')
        REQUEST_SYS_ID=$(echo $RESPONSE | jq -r '.result.sys_id')
        
        if [ "$REQUEST_NUMBER" != "null" ]; then
          echo "✅ Request created: $REQUEST_NUMBER"
          echo "request_number=$REQUEST_NUMBER" >> $GITHUB_OUTPUT
          echo "request_sys_id=$REQUEST_SYS_ID" >> $GITHUB_OUTPUT
        else
          echo "❌ Failed to create request"
          echo "Response: $RESPONSE"
          exit 1
        fi
        
    - name: Read Request Back
      run: |
        echo "Reading request back..."
        REQUEST_SYS_ID="${{ steps.create_request.outputs.request_sys_id }}"
        
        RESPONSE=$(curl -s -X GET \
          "https://${SERVICENOW_INSTANCE}/api/now/table/sc_request/${REQUEST_SYS_ID}" \
          -H "Accept: application/json" \
          -H "Authorization: Basic $(echo -n ${SERVICENOW_USERNAME}:${SERVICENOW_PASSWORD} | base64)")
        
        REQUEST_STATE=$(echo $RESPONSE | jq -r '.result.request_state')
        APPROVAL=$(echo $RESPONSE | jq -r '.result.approval // "not_requested"')
        
        echo "✅ Request read successfully"
        echo "Request Number: ${{ steps.create_request.outputs.request_number }}"
        echo "Request State: $REQUEST_STATE"
        echo "Approval Status: $APPROVAL"
        
    - name: Update Request with Test Results
      run: |
        echo "Updating request with test results..."
        REQUEST_SYS_ID="${{ steps.create_request.outputs.request_sys_id }}"
        
        WORK_NOTES="GitHub Action test completed successfully\\nTest run: ${{ github.run_id }}\\nCompleted at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        
        curl -s -X PUT \
          "https://${SERVICENOW_INSTANCE}/api/now/table/sc_request/${REQUEST_SYS_ID}" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -H "Authorization: Basic $(echo -n ${SERVICENOW_USERNAME}:${SERVICENOW_PASSWORD} | base64)" \
          -d '{
            "work_notes": "'"$WORK_NOTES"'",
            "close_notes": "GitHub Action test completed successfully"
          }'
        
        echo "✅ Request updated with test results"
        
    - name: Print Test Summary
      if: always()
      run: |
        echo ""
        echo "========================================"
        echo "        SERVICENOW TEST SUMMARY"
        echo "========================================"
        echo "Request Number: ${{ steps.create_request.outputs.request_number }}"
        echo "Repository: ${{ github.repository }}"
        echo "Commit: ${{ github.sha }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Test Run ID: ${{ github.run_id }}"
        echo ""
        echo "ServiceNow URL: https://${{ env.SERVICENOW_INSTANCE }}/nav_to.do?uri=sc_request.do?sys_id=${{ steps.create_request.outputs.request_sys_id }}"
        echo "========================================"